import Head from "next/head";
import Link from "next/link";

export default function Index() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href={"/login"}>
        <button>Login</button>
      </Link>

      <Link href={"/memberships"}>
        <button>Get my membership data</button>
      </Link>
    </div>
  );
}
